# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'history.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_History(object):
    def __init__(self):
        super(Ui_History, self).__init__
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 10, 761, 531))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setColumnWidth(0, 110)
        self.tableWidget.setColumnWidth(1, 85)
        self.tableWidget.setColumnWidth(2, 65)
        self.tableWidget.setColumnWidth(3, 160)
        self.tableWidget.setColumnWidth(4, 160)
        self.tableWidget.setColumnWidth(5, 160)
        self.tableWidget.setRowCount(0)
        self.load_initial_data()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "History"))

    def load_initial_data(self):
        import sqlite3, os.path
        BASE_DIR = os.path.dirname(os.path.abspath(__file__))
        db_path = os.path.join(BASE_DIR, "history.db")
        conn = sqlite3.connect(db_path)
        cursor = conn.cursor()

        cursor.execute('''SELECT * FROM RESULTS''')
        rows = cursor.fetchall()

        for row in rows:
            inx = rows.index(row)
            self.tableWidget.insertRow(inx)
            # add more if there is more columns in the database.
            self.tableWidget.setHorizontalHeaderLabels(["Date", "Time", "Ticker", "High", "Low", "Close"])
            self.tableWidget.setItem(inx, 0, QtWidgets.QTableWidgetItem(row[0]))
            self.tableWidget.setItem(inx, 1, QtWidgets.QTableWidgetItem(row[1]))
            self.tableWidget.setItem(inx, 2, QtWidgets.QTableWidgetItem(row[2]))
            self.tableWidget.setItem(inx, 3, QtWidgets.QTableWidgetItem(str(row[3])))
            self.tableWidget.setItem(inx, 4, QtWidgets.QTableWidgetItem(str(row[4])))
            self.tableWidget.setItem(inx, 5, QtWidgets.QTableWidgetItem(str(row[5])))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_History()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
